language: php

cache:
  directories:
    - $HOME/.composer/cache

jobs:
  include:
    - php: "7.1"
      env: LARAVEL='5.5.*'
    - php: "7.1"
      env: LARAVEL='5.6.*'
    - php: "7.1"
      env: LARAVEL='5.7.*'
    - php: "7.1"
      env: LARAVEL='5.8.*'
    - php: "7.2"
      env: LARAVEL='5.5.*'
    - php: "7.2"
      env: LARAVEL='5.6.*'
    - php: "7.2"
      env: LARAVEL='5.7.*'
    - php: "7.2"
      env: LARAVEL='5.8.*'
    - php: "7.2"
      env: LARAVEL='^6.0'
    - php: "7.3"
      env: LARAVEL='5.5.*'
    - php: "7.3"
      env: LARAVEL='5.6.*'
    - php: "7.3"
      env: LARAVEL='5.7.*'
    - php: "7.3"
      env: LARAVEL='5.8.*'
    - php: "7.3"
      env: LARAVEL='^6.0'

install:
  - composer require "laravel/framework:${LARAVEL}" --no-interaction --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit --colors=always --verbose
