# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  pull_request:
  push:
    branches:
      - master

name: "Continuous Integration"

jobs:
  composer-normalize:
    name: "composer-normalize"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: "Run composer normalize"
        uses: docker://ergebnis/composer-normalize-action:0.8.0

      - uses: "stefanzweifel/git-auto-commit-action@v4"
        with:
          commit_message: Normalize composer.json
          branch: ${{ github.head_ref }}

  coding-standards:
    name: "Coding Standards"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Validate composer.json and composer.lock"
        run: composer validate

      - name: "Install locked dependencies with composer"
        run: composer install --no-interaction --no-progress

  tests:
    name: "Tests"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.3
          - 7.4
          - 8.0

        laravel-version:
          - 5.7.*
          - 5.8.*
          - ^6
          - ^7
          - ^8

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: "mbstring"
          php-version: ${{ matrix.php-version }}

      - name: "Install dependencies with composer"
        run: composer require illuminate/contracts:${{ matrix.laravel-version }} --no-interaction --prefer-dist --no-interaction

      - name: "Run unit tests with phpunit/phpunit"
        run: vendor/bin/phpunit

      - name: "Run static analysis with phpstan"
        run: vendor/bin/phpstan analyse

  code-coverage:
    name: "Code Coverage"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install locked dependencies with composer"
        run: composer install --no-interaction --no-progress

      - name: "Dump Xdebug filter with phpunit/phpunit"
        run: vendor/bin/phpunit --dump-xdebug-filter=.build/phpunit/xdebug-filter.php

      - name: "Collect code coverage with Xdebug and phpunit/phpunit"
        run: vendor/bin/phpunit --coverage-clover=build/logs/clover.xml --prepend=.build/phpunit/xdebug-filter.php

      # Not using codecov/codecov-action for now, as the build is prohibitively slow
      - name: "Download code coverage uploader for Codecov.io"
        run: curl -s https://codecov.io/bash -o codecov

      - name: "Send code coverage report to Codecov.io"
        run: bash codecov -t ${{ secrets.CODECOV_TOKEN }}
